title: System Admin Toolkit (SAT)
theme: hugo-theme-learn
baseURL: /docs-sat/
languageCode: en-US
defaultContentLanguage: en-26
defaultContentLanguageInSubdir: true
showVisitedLinks: true
refLinksErrorLevel: WARNING
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  shortTitle: System Admin Toolkit
  themeVariant: blue
  disableNextPrev: true
  disableLandingPageButton: true
languages:
  en-26:
    contentDir: content/2.6
    languageName: '2.6'
    weight: 40
    landingPageURL: /docs-sat/en-26
  en-25:
    contentDir: content/2.5
    languageName: '2.5'
    weight: 40
    landingPageURL: /docs-sat/en-25
  en-24:
    contentDir: content/2.4
    languageName: '2.4'
    weight: 40
    landingPageURL: /docs-sat/en-24
  en-23:
    contentDir: content/2.3
    languageName: '2.3'
    weight: 40
    landingPageURL: /docs-sat/en-23
  en-22:
    contentDir: content/2.2
    languageName: '2.2'
    weight: 40
    landingPageURL: /docs-sat/en-22
  en-21:
    contentDir: content/2.1
    languageName: '2.1'
    weight: 40
    landingPageURL: /docs-sat/en-21
