---
name: Generate CSM Docs
on: [workflow_dispatch]
jobs:
  Generate-CSM-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Generator
        run: |
          ./bin/build.sh
      - name: Do a listing
        run: |
          printenv
          git status
          ls -al 
      - run: echo "This job's status is ${{ job.status }}."